# Set language to `none` because if set to `cpp` CXX and C environment variables
# are overriden with those of older versions
language: none

env:
    global:
        - CXX=g++-5

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - lcov

notifications:
    email: false

cache:
    directories:
        # Cache gtest sources
        - test/build/googletest-build
        - test/build/googletest-src
        - test/build/googletest-download

# Build the project
script:
    - bash test/build_and_run_ut.sh

after_success:
    - bash run_coverage.sh
    # Upload report to codecov
    - bash <(curl -s https://codecov.io/bash) -s coverage-reports || echo "Codecov did not collect coverage reports"
