# Set language to `none` because if set to `cpp` CXX and C environment variables
# are overriden with those of older versions
language: none

env:
    global:
        - CXX=g++-5

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - lcov
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
            - cppcheck

notifications:
    email: false

cache:
    directories:
        # Cache gtest sources
        - test/build/googletest-build
        - test/build/googletest-src
        - test/build/googletest-download
        - ~/arduino_ide
        - ~/.arduino15/packages/

before_install:
  # Set up the environment for building with the Arduino IDE
  - export ARDUINO_IDE_VERSION="1.8.11"
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "ESP32 AnalogWrite"
# - arduino --install-library "ESP32ArduinoServo"

script:
    # Build and run unit tests
    - bash test/build_and_run_ut.sh
    # Run static code analysis over the source code
    - cppcheck --std=c++11 --enable=performance,portability,information --quiet --error-exitcode=1 src/
    # Ensure examples are buildable for various boards
    - build_platform uno
    - build_platform mega2560
    - build_platform leonardo
    - build_platform esp8266
    - build_platform esp32

after_success:
    - bash run_coverage.sh
    # Upload report to codecov
    - bash <(curl -s https://codecov.io/bash) -s coverage-reports || echo "Codecov did not collect coverage reports"
    # Generate documentation
    - doxygen Doxyfile

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  on:
    branch: master
