name: Commit message

on: [pull_request]

jobs:
  check-commit-message:
    runs-on: ubuntu-20.04
    steps:
      - name: Verify commit messages follow best practices in CI
        uses: platisd/bad-commit-message-blocker@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
