name: Duplicate code

on: issue_comment

jobs:
  duplicate-code-check:
    name: Check for duplicate code
    # Trigger the tool only when a comment containing the keyword is published in a pull request
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'run_duplicate_code_detection_tool')
    runs-on: ubuntu-20.04
    steps:
      - name: duplicate_code
        uses: platisd/duplicate-code-detection-tool@write_markdown_to_workspace
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directories: "src"
          ignore_below: 5
          file_extensions: "c, cpp"
          warn_above: 15
          fail_above: 60
      - name: Print contents
        run: ls -lah
      - name: Run tree
        run: |
          sudo apt-get install tree
          tree
      - name: Print output
        run: echo "The selected color is ${{ steps.duplicate_code.outputs.markdown }}"
